version: "3"

services:
  backend:
    image: ghcr.io/${GITHUB_USER}/${DOCKER_IMAGE_NAME}:dev
    ports:
      - "80:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqlDb:3306/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true
      - spring.datasource.username=${MYSQL_USER}
      - spring.datasource.password=${MYSQL_PASSWORD}
      - spring.jpa.properties.hibernate.jdbc.time_zone=UTC
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.open-in-view=false
      - spring.data.jpa.repositories.bootstrap_mode=default
    networks:
      - backend-net
    depends_on:
      - mysqlDb
    restart: unless-stopped

  mysqlDb:
    image: mysql:latest
    ports:
      - "3306:3306"
    networks:
      - backend-net
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: unless-stopped

networks:
  backend-net: { }
